'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const root=__dirname,dir=path.join(root,'bank-source');
const legacy=JSON.parse(fs.readFileSync(path.join(dir,'legacy-categories.json'),'utf8'));
const clean=s=>s.normalize('NFC').replace(/[\u00ad\u200b-\u200d\ufeff]/g,'').trim();
const normalize=s=>clean(s).toLocaleLowerCase('sv').replace(/^(?:vad är|vem är|vilka är)\s+/,'').replace(/^(?:en|ett|de|den|det|att)\s+/,'').replace(/[^\p{L}\p{N}]+/gu,' ').trim();
const personCats=new Set(['Nordisk mytologi','Grekisk och romersk mytologi']);
const personNames=new Set(['Tor','Oden','Loke','Freja','Balder','Heimdall','Tyr','Hel','Frigg','Idun','Skade','Siv','Frej','Njord','Pierre de Coubertin','Louis Braille','Dmitrij Mendelejev','Jesse Owens','Billie Jean King','Akira Kurosawa','Charlie Chaplin','Bob Dylan','Sokrates','Platon','Aristoteles','Hannibal','Nadia Comăneci']);
const groupNames=new Set(['Hugin och Munin','IJustWantToBeCool','Jocke och Jonna','Matkoma','Suffragetterna']);
const thingCreators=new Set(['Uppdrag Mat','Veritasium','SmarterEveryDay']);
const cats=[];let cat;
for(const file of fs.readdirSync(dir).filter(f=>/^\d.*\.txt$/.test(f)).sort()){
 for(const [lineNumber,line] of fs.readFileSync(path.join(dir,file),'utf8').split(/\r?\n/).entries()){
  const l=clean(line);if(!l)continue;
  if(l.startsWith('@')){const [name,form,template]=l.slice(1).split('|');cat={id:'v05-'+normalize(name).replaceAll(' ','-'),name,form,template,rows:[],file};cats.push(cat);continue;}
  const [answer,...facts]=l.split('|');const clue=cat.template?cat.template.replace(/\{(\d+)\}/g,(_,n)=>facts[n-1]??'MISSING'):facts.join('|');
  cat.rows.push({rawAnswer:answer,clue,location:file+':'+(lineNumber+1)});
 }
}
function make(raw,category,index,final=false){
 const aliases=raw.rawAnswer.split('~').map(clean),label=aliases[0];
 let form=category.form||'Vad är';if(personNames.has(label))form='Vem är';if(groupNames.has(label))form='Vilka är';if(thingCreators.has(label))form='Vad är';
 const answer=form+' '+label.replace(/\?$/,'')+'?';
 const key=normalize(label),id=(final?'f05-':'q05-')+crypto.createHash('sha256').update(category.name+'|'+key).digest('hex').slice(0,14);
 return {id,clue:clean(raw.clue),answer,key,aliases,level:final?null:Math.floor(index/5)+1,...(final?{category:category.name}:{})};
}
const BANK=cats.map(c=>({...c,questions:c.rows.map((r,i)=>make(r,c,i))}));
const FINALS=fs.readFileSync(path.join(dir,'finals.txt'),'utf8').split(/\r?\n/).map(clean).filter(Boolean).map((l,i)=>{const [category,rawAnswer,clue]=l.split('|');return make({rawAnswer,clue},{name:category},i,true)});
const errors=[],warnings=[],registry=new Map(),all=[...BANK.flatMap(c=>c.questions),...FINALS];
if(BANK.length!==100)errors.push('Categories '+BANK.length);
if(FINALS.length!==80)errors.push('Finals '+FINALS.length);
for(const c of BANK)if(c.rows.length!==25)errors.push(c.name+': '+c.rows.length+' rows');
for(const q of all){
 const text=normalize(q.clue);if(q.clue.length<35||q.clue.includes('???')||/\bersätt\b|placeholder|MISSING|ska ersättas/i.test(q.clue+q.answer))errors.push('Unfinished '+q.answer);
 if(!/^(Vad|Vem|Vilka) är .+\?$/.test(q.answer))errors.push('Answer format '+q.answer);
 for(const a of new Set(q.aliases.map(normalize))){
  const other=registry.get(a);if(other&&other.id!==q.id)errors.push('Duplicate '+a+': '+other.answer+' / '+q.answer);registry.set(a,q);
  if(a&&(a.length>2?text.includes(a):(' '+text+' ').includes(' '+a+' ')))errors.push('Leak '+q.answer+' :: '+q.clue);
 }
}
const data=BANK.map(c=>({id:legacy.find(old=>old.name===c.name)?.id||c.id,name:c.name,levels:Array.from({length:5},(_,i)=>c.questions.slice(i*5,i*5+5))}));
const metadata={version:'0.5',categories:data.length,ordinary:data.reduce((n,c)=>n+c.levels.flat().length,0),finals:FINALS.length,errors,warnings};
fs.mkdirSync(path.join(root,'review'),{recursive:true});fs.writeFileSync(path.join(root,'review/bank-validation.json'),JSON.stringify(metadata,null,2));
if(errors.length){console.error(errors.join('\n'));process.exitCode=1;}else{
 const aliases=Object.fromEntries([...registry].map(([a,q])=>[a,q.key]));
 fs.writeFileSync(path.join(root,'dist/data.js'),'/* QuizStorm 0.5. Generated by build-bank.cjs from reviewed bank-source. */\nconst BANK='+JSON.stringify(data)+';\nconst FINALS='+JSON.stringify(FINALS)+';\nconst ALL_CATEGORIES=BANK.map(c=>c.name);\nconst ANSWER_ALIASES='+JSON.stringify(aliases)+';\nconst normalizeAnswer='+normalize.toString().replace('clean(s)',"s.normalize('NFC').replace(/[\\u00ad\\u200b-\\u200d\\ufeff]/g,'').trim()")+';\nconst answerKey=s=>ANSWER_ALIASES[normalizeAnswer(s)]||normalizeAnswer(s);\n');
 console.log(JSON.stringify(metadata));
}
