const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict');
const elements=new Map();function el(s){if(!elements.has(s))elements.set(s,{innerHTML:'',textContent:'',value:'',style:{},open:false,classList:{add(){},remove(){},toggle(){}},showModal(){this.open=true},close(){this.open=false},addEventListener(){}});return elements.get(s)}
const ctx={console,Intl,Date,Math,JSON,Number,String,Set,Map,Array,Object,Error,AbortController,setTimeout:()=>0,clearTimeout(){},setInterval(){},document:{querySelector:el,querySelectorAll:()=>[],body:{classList:{add(){},remove(){},toggle(){}}},addEventListener(){}},window:{addEventListener(){}},localStorage:{setItem(){},getItem(){return null}},assert};vm.createContext(ctx);for(const p of ['effects.js','data.js','app.js'])vm.runInContext(fs.readFileSync(__dirname+'/dist/'+p,'utf8'),ctx);const run=s=>vm.runInContext(s,ctx);
run(`assert.equal(BANK.length,100);assert.equal(ALL_CATEGORIES.length,100);assert.equal(new Set(ALL_CATEGORIES).size,100);assert.equal(FINALS.length,80);const questions=BANK.flatMap(c=>c.levels.flat());assert.equal(questions.length,2500);assert.equal(new Set(questions.map(q=>q.key)).size,2500);assert(FINALS.every(f=>!questions.some(q=>q.key===f.key)));for(const q of questions){assert(q.clue.length>30);assert(!(q.key.length>2?normalizeAnswer(q.clue).includes(q.key):(' '+normalizeAnswer(q.clue)+' ').includes(' '+q.key+' ')),'Facit läcker: '+q.key)};`);
run(`createGame();game.doubleCell=29;openClue(0,0);assert.equal(active.selected,null);assert($('#dialog').innerHTML.includes('class="answer-blurred"'));toggleAnswer();assert(!$('#dialog').innerHTML.includes('class="answer-blurred"'));toggleAnswer();assert($('#dialog').innerHTML.includes('class="answer-blurred"'));toggleTimer();assert(!active.running);selectRespondent(0);judge(false);assert.equal(game.players[0].score,-100);assert.equal(game.players[1].score,0);assert(active.failed.includes(0));selectRespondent(0);assert.equal(active.selected,null);undoJudge();assert.equal(game.players[0].score,0);judge(false,true);assert.equal(game.players[0].score,-100);selectRespondent(1);judge(true);assert.equal(active,null);assert(!$('#dialog').open);assert(game.board[0].cells[0].done);assert.equal(game.players[1].score,100);assert.equal(game.chooser,1);`);
run(`openClue(0,1);selectRespondent(1);toggleTimer();const previous=game.players.map(p=>p.score);noMoreAnswers();assert.equal(active,null);assert.deepEqual(game.players.map(p=>p.score),previous);assert(game.board[0].cells[1].done);openClue(0,2);noMoreAnswers();assert.equal(active,null);assert.deepEqual(game.players.map(p=>p.score),previous);openClue(0,3);selectRespondent(1);judge(false);const afterWrong=game.players.map(p=>p.score);noMoreAnswers();assert.equal(active,null);assert.deepEqual(game.players.map(p=>p.score),afterWrong);`);
run(`game.doubleCell=4;openClue(0,4);assert.equal(active.stage,'bet');setDoublePlayer(0);assert.equal(maxBet(0),1500);$('#double-bet').value='1501';revealDouble();assert.equal(active.stage,'bet');$('#double-bet').value='1500';revealDouble();selectRespondent(1);assert.equal(active.selected,0);judge(true);assert.equal(active,null);assert.equal(game.players[0].score,1400);`);
run(`nextRound(true);assert.equal(game.round,2);assert.equal(game.chooser,1);assert(game.board.every(c=>!game.usedCategories.includes(c.id)));assert.equal(game.board[0].cells[4].value,1000);nextRound(true);assert.equal(game.round,3);assert.equal(game.board[0].cells[4].value,1500);nextRound(true);assert.equal(game.phase,'final');assert.equal(game.final.eligible.length,1);assert.equal(game.final.eligible[0],0);$('#final-bet-0').value='100';lockFinalBets();endFinalThinking();gradeFinal(0,true);finishFinal();assert.equal(game.players[0].score,1500);assert.equal(game.phase,'result');`);
run(`createGame();game.doubleCell=29;openClue(0,0);selectRespondent(0);judge(false,true);selectRespondent(1);judge(false,true);assert(active.resolved);assert.equal(game.players[1].score,-100);finishClue();nextRound(true);assert.equal(game.round,1);beginNextRound(1);assert.equal(game.round,2);game.round=3;nextRound(true);assert.equal(game.phase,'result');assert(game.noFinal);`);
run(`for(let t=0;t<50;t++){createGame();let cat=game.board.map(c=>c.id);let keys=game.board.flatMap(c=>c.cells.map(q=>q.key));for(let r=0;r<2;r++){game.players[0].score=-10;nextRound(true);cat.push(...game.board.map(c=>c.id));keys.push(...game.board.flatMap(c=>c.cells.map(q=>q.key)))}assert.equal(new Set(cat).size,18);assert.equal(new Set(keys).size,90)}`);
console.log('PASS: blurred-answer toggle, immediate close on right/no-answer, wrong-answer lockout and scoring, timers, double chance, rounds, final, and 50 unique random boards.');

run(`createGame();game.doubleCell=29;openClue(0,0);assert(!active.running);selectRespondent(0);assert(active.running);const firstDeadline=active.deadline;toggleTimer();assert(!active.running);assert(active.remaining>0);toggleTimer();assert(active.running);judge(false);assert(!active.running);selectRespondent(0);assert.equal(active.selected,null);assert(!active.running);selectRespondent(1);assert(active.running);assert.equal(active.remaining,game.seconds*1000);noMoreAnswers();game.doubleCell=1;openClue(0,1);assert(!active.running);$('#double-bet').value='100';revealDouble();assert(active.running);toggleTimer();assert(!active.running);`);
console.log('PASS: selection starts timer, manual pause/resume, failed-player lockout and double timer starts only after reveal.');

run(`createGame();game.doubleCell=29;openClue(0,0);selectRespondent(0);assert(active.running);const deadlineBefore=active.deadline;toggleAnswer();assert(active.running);assert.equal(active.deadline,deadlineBefore);toggleAnswer();assert(active.running);assert.equal(active.deadline,deadlineBefore);toggleTimer();const pausedRemaining=active.remaining;toggleAnswer();assert(!active.running);assert.equal(active.remaining,pausedRemaining);noMoreAnswers();renderMenu();const html=$('#app').innerHTML;const ordinary=html.split('id="seconds">')[1].split('</select>')[0];const final=html.split('id="finalSeconds">')[1].split('</select>')[0];assert.equal(Array.from(ordinary.matchAll(/value="([0-9]+)"/g),m=>+m[1]).join(","),"5,10,20,30");assert.equal(Array.from(final.matchAll(/value="([0-9]+)"/g),m=>+m[1]).join(","),"30,45,60");assert(!html.includes('Svaret står på skärmen'));assert(!html.includes('class="pills"'));assert(!html.includes('Testversion ·'));`);
console.log('PASS: reveal preserves running/paused timers and deadlines; exact time options and menu cleanup.');

run(`createGame();const chooserBefore=game.chooser;openScoreEditor(0);$('#score-correction').value='-500';saveScoreCorrection(0);assert.equal(game.players[0].score,-500);assert.equal(game.players[1].score,0);assert.equal(game.chooser,chooserBefore);openScoreEditor(0);$('#score-correction').value='1 200';saveScoreCorrection(0);assert.equal(game.players[0].score,1200);openScoreEditor(0);for(const bad of ['','abc','1.5','1e3','9007199254740992']){$('#score-correction').value=bad;saveScoreCorrection(0);assert.equal(game.players[0].score,1200);assert($('#dialog').open)}closeModal();assert.equal(game.players[0].score,1200);openScoreEditor(0);$('#score-correction').value='0';saveScoreCorrection(0);assert.equal(game.players[0].score,0);assert($('#app').innerHTML.includes('beginScoreHold(event,0)'));`);
console.log('PASS: score editing, negative/zero totals, invalid input, cancellation and unchanged turn.');
